name: Build

on:
  push:
    branches: master
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Login to docker hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
     
        
      - name: Build and push stable-rolling
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            wascardev/dolibarr-arm:latest-rolling

      - name: Build and push stable
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./13.0.0/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
           wascardev/dolibarr-arm:latest
            
      - name: Build and push old version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./12.0.4/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
           wascardev/dolibarr-arm:12.0.4

